# ============================================================
# gag_games.py - 128+ Demo Games (Pragmatic + JILI + PG Soft + BGaming + Habanero)
# ============================================================

# ==================== PRAGMATIC PLAY (40) ====================
PRAGMATIC_GAMES = [
    {"title":"Gates of Olympus","img":"https://i.ibb.co/23xL2PYd/Gates-of-Olympus.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs20olympgate&jurisdiction=99","badge":"hot"},
    {"title":"Sweet Bonanza","img":"https://i.ibb.co/q3br7FMz/Sweet-Bonanza.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?gameSymbol=vs20fruitsw&jurisdiction=99&lang=EN&cur=MMK","badge":"hot"},
    {"title":"Starlight Princess","img":"https://i.ibb.co/JFm79SK6/Starlight-Princess.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs20starlight&jurisdiction=99","badge":"hot"},
    {"title":"Sugar Rush 1000","img":"https://i.ibb.co/B5H2Qd0m/Sugar-Rush-1000.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?stylename=demo_clienthub&lang=en&cur=MMK&gameSymbol=vs20sugrushss&jurisdiction=99","badge":"new"},
    {"title":"Big Bass Bonanza 1000","img":"https://i.ibb.co/Y4785Lf9/Big-Bass-Bonanza-1000.png","url":"https://demogamesfree.pragmaticplay.net/hub-demo/openGame.do?lang=en&cur=MMK&gameSymbol=vs10bbbnz1000&jurisdiction=99","badge":"hot"},
    {"title":"The Dog House Megaways","img":"https://i.ibb.co/SD0078rF/The-Dog-House-Megaways.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vswaysdogs&jurisdiction=99"},
    {"title":"Zeus vs Hades","img":"https://i.ibb.co/Tq8pQKwC/Zeus-vs-Hades-Gods-of-War.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs15godsofwar&jurisdiction=99"},
    {"title":"Gates of Olympus Super Scatter","img":"https://i.ibb.co/Z6ZH1GCB/Gates-of-Olympus-Super-Scatter.png","url":"https://demogamesfree.pragmaticplay.net/hub-demo/openGame.do?lang=en&cur=MMK&gameSymbol=vs20olympgold&jurisdiction=99","badge":"new"},
    {"title":"Starlight Princess 1000","img":"https://i.ibb.co/mCvZ5P9z/Starlight-Princess-1000.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&jurisdiction=99&gameSymbol=vs20starlightx","badge":"new"},
    {"title":"Pyramid Bonanza","img":"https://i.ibb.co/nNhs9Lj8/Pyramid-Bonanza.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?jurisdiction=99&lang=en&cur=MMK&gameSymbol=vs20pbonanza"},
    {"title":"Mahjong Wins Super Scatter","img":"https://i.ibb.co/zW4qW1vr/Mahjong-Wins-Super-Scatter.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vswaysmwss&jurisdiction=99","badge":"hot"},
    {"title":"5 Lions Megaways","img":"https://i.ibb.co/TMdMMMjC/5-Lions-Megaways.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vswayslions&jurisdiction=99"},
    {"title":"Gates of Hades","img":"https://i.ibb.co/z383NVV/Gates-of-Hades.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs20gtsofhades&jurisdiction=99","badge":"hot"},
    {"title":"Hand of Midas","img":"https://i.ibb.co/m5ngwLCJ/Hand-of-Midas.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs20midas&jurisdiction=99"},
    {"title":"Wild West Gold","img":"https://i.ibb.co/2Y34Mz8G/Wild-West-Gold.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs40wildwest&jurisdiction=99"},
    {"title":"Buffalo King","img":"https://i.ibb.co/VY1LyJKy/Buffalo-King.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs4096bufking&jurisdiction=99"},
    {"title":"Fire Stampede","img":"https://i.ibb.co/GQwxn98k/Fire-Stampede.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vswaysstampede&jurisdiction=99","badge":"hot"},
    {"title":"Sweet Bonanza Super Scatter","img":"https://i.ibb.co/9mtnRqvn/Sweet-Bonanza-Super-Scatter.png","url":"https://demogamesfree.pragmaticplay.net/hub-demo/openGame.do?lang=en&cur=MMK&gameSymbol=vs20swbonsup&jurisdiction=99","badge":"new"},
    {"title":"Mahjong Wins 2","img":"https://i.ibb.co/NnLfNWZT/Mahjong-Wins-2.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vswaysmahwin2&jurisdiction=99"},
    {"title":"Bigger Barn House Bonanza","img":"https://i.ibb.co/FkMxcPKX/Bigger-Barn-House-Bonanza.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vswaysbbarnh&jurisdiction=99"},
    {"title":"888 Dragons","img":"https://i.ibb.co/gLtSwgXY/888-Dragons-Slot.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs1dragon8"},
    {"title":"7 Clovers of Fortune","img":"https://i.ibb.co/1YvqsF2s/7-Clovers-of-Fortune.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vswayssevenc&jurisdiction=99"},
    {"title":"Lucky Monkey","img":"https://i.ibb.co/YF0g05cH/Lucky-Monkey.png","url":"https://demogamesfree.pragmaticplay.net/hub-demo/openGame.do?lang=en&cur=MMK&gameSymbol=vs5luckymly&jurisdiction=99"},
    {"title":"Olympus Wins","img":"https://i.ibb.co/bgTFFK32/Olympus-Wins.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vswaysolwfp&jurisdiction=99"},
    {"title":"Pig Farm","img":"https://i.ibb.co/YFJ0vVqy/Pig-Farm.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs25pfarmfp&jurisdiction=99"},
    {"title":"Wild Wildebeest Wins","img":"https://i.ibb.co/ksyqLkP5/Wild-Wildebeest-Wins.png","url":"https://demogamesfree.pragmaticplay.net/hub-demo/openGame.do?lang=en&cur=MMK&gameSymbol=vswaysbufstamp&jurisdiction=99"},
    {"title":"Greedy Fortune Pig","img":"https://i.ibb.co/bMMDrWBw/Greedy-Fortune-Pig.png","url":"https://demogamesfree.pragmaticplay.net/hub-demo/openGame.do?lang=en&cur=MMK&gameSymbol=vs10fortnpig&jurisdiction=99"},
    {"title":"5 Lions Megaways 2","img":"https://i.ibb.co/VcnYZws7/5-Lions-Megaways-2.png","url":"https://demogamesfree.pragmaticplay.net/hub-demo/openGame.do?lang=en&cur=MMK&gameSymbol=vsways5lions2&jurisdiction=99","badge":"new"},
    {"title":"Zeus vs Hades 250","img":"https://i.ibb.co/fVGYPW8F/zeus-vs-hades-gods-of-war-250-logo.webp","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs15zeushadseq&jurisdiction=99","badge":"new"},
    {"title":"Gates of Gatot Kaca 1000","img":"https://i.ibb.co/RTFbhCT7/Gates-of-Gatot-Kaca-1000.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs20gatotx&jurisdiction=99","badge":"new"},
    {"title":"Brick House Bonanza","img":"https://i.ibb.co/DDhYgNFT/Brick-House-Bonanza.png","url":"https://demogamesfree.pragmaticplay.net/hub-demo/openGame.do?lang=en&cur=MMK&gameSymbol=vswaysbrickhos&jurisdiction=99"},
    {"title":"Wild Bison Charge","img":"https://i.ibb.co/2Y3HYVw3/Wild-Bison-Charge.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs20stickywild&jurisdiction=99"},
    {"title":"Sugar Rush","img":"https://i.ibb.co/B5H2Qd0m/Sugar-Rush-1000.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs20sugarrush&jurisdiction=99"},
    {"title":"Candy Blitz","img":"https://i.ibb.co/q3br7FMz/Sweet-Bonanza.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs20candyblitz&jurisdiction=99"},
    {"title":"Release the Kraken","img":"https://i.ibb.co/23xL2PYd/Gates-of-Olympus.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs20kraken&jurisdiction=99"},
    {"title":"John Hunter","img":"https://i.ibb.co/nNhs9Lj8/Pyramid-Bonanza.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs20johnhunter&jurisdiction=99"},
    {"title":"Fruit Party","img":"https://i.ibb.co/q3br7FMz/Sweet-Bonanza.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs20fruitparty&jurisdiction=99"},
    {"title":"Rise of Samurai","img":"https://i.ibb.co/z383NVV/Gates-of-Hades.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs20samurai&jurisdiction=99"},
    {"title":"Big Bass Splash","img":"https://i.ibb.co/Y4785Lf9/Big-Bass-Bonanza-1000.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs10bbsplash&jurisdiction=99","badge":"hot"},
    {"title":"The Dog House","img":"https://i.ibb.co/SD0078rF/The-Dog-House-Megaways.png","url":"https://demogamesfree.pragmaticplay.net/gs2c/openGame.do?lang=en&cur=MMK&gameSymbol=vs20doghouse&jurisdiction=99"},
]

# ==================== JILI (38) ====================
JILI_GAMES = [
    {"title":"Money Coming","img":"https://i.ibb.co/Y7BqkTRC/Money-Coming.png","url":"https://jiligames.com/PlusTrial/51/my-MM","badge":"hot"},
    {"title":"Fortune Gems","img":"https://i.ibb.co/n8fn7MJz/Fortune-Gems.png","url":"https://jiligames.com/PlusTrial/109/my-MM","badge":"hot"},
    {"title":"Golden Empire 2","img":"https://i.ibb.co/mC4Hgy8v/Golden-Empire-2.png","url":"https://jiligames.com/PlusTrial/424/my-MM"},
    {"title":"Mines","img":"https://i.ibb.co/wFrrQsvj/Mines.png","url":"https://jiligames.com/PlusTrial/229/my-MM","badge":"new"},
    {"title":"Fortune Gems 2","img":"https://i.ibb.co/LXRVr2mC/Fortune-Gems-2.png","url":"https://jiligames.com/PlusTrial/223/my-MM","badge":"hot"},
    {"title":"Jackpot Fishing","img":"https://i.ibb.co/sp91m65J/Jackpot-Fishing.png","url":"https://jiligames.com/PlusTrial/32/my-MM"},
    {"title":"Charge Buffalo","img":"https://i.ibb.co/MxDHkb4K/Charge-Buffalo.png","url":"https://jiligames.com/PlusTrial/47/my-MM","badge":"hot"},
    {"title":"Fortune Coins 2","img":"https://i.ibb.co/nsJRwZMB/Fortune-Coins.png","url":"https://jiligames.com/PlusTrial/523/my-MM","badge":"new"},
    {"title":"Super Ace","img":"https://i.ibb.co/Nn9F85Vn/Super-Ace.png","url":"https://jiligames.com/PlusTrial/49/my-MM"},
    {"title":"Boxing King","img":"https://i.ibb.co/0pLK97L5/Boxing-King.png","url":"https://jiligames.com/PlusTrial/77/my-MM"},
    {"title":"Bao Boon Chin","img":"https://i.ibb.co/JjHSbJdz/Bao-boon-chin.png","url":"https://jiligames.com/PlusTrial/36/my-MM"},
    {"title":"Chin Shi Huang","img":"https://i.ibb.co/4nN9rHy7/Chin-Shi-Huang.png","url":"https://jiligames.com/PlusTrial/2/my-MM"},
    {"title":"Happy Fishing","img":"https://i.ibb.co/1f6VxLND/Happy-Fishing.png","url":"https://jiligames.com/PlusTrial/82/my-MM"},
    {"title":"Ali Baba","img":"https://i.ibb.co/v64ndgV1/Ali-Baba.png","url":"https://jiligames.com/PlusTrial/110/my-MM"},
    {"title":"Coin Tree","img":"https://i.ibb.co/Q37L44t6/Coin-Tree.png","url":"https://jiligames.com/PlusTrial/392/my-MM"},
    {"title":"Money Pot","img":"https://i.ibb.co/wZh9w0DZ/Money-Pot.png","url":"https://jiligames.com/PlusTrial/379/my-MM"},
    {"title":"Coin Wild Horse","img":"https://i.ibb.co/848ggqZf/3-Coin-Wild-Horse.png","url":"https://jiligames.com/PlusTrial/485/my-MM","badge":"new"},
    {"title":"3 Charge Buffalo","img":"https://i.ibb.co/TMKvN7ft/3-Charge-Buffalo.png","url":"https://jiligames.com/PlusTrial/460/my-MM","badge":"new"},
    {"title":"Fish Prawn Crab","img":"https://i.ibb.co/zWwqTByT/Fish-Prawn-Crab.png","url":"https://jiligames.com/PlusTrial/389/my-MM"},
    {"title":"Fengshen","img":"https://i.ibb.co/rRqHPvzx/Fengshen.png","url":"https://jiligames.com/PlusTrial/38/my-MM"},
    {"title":"Golden Bank","img":"https://i.ibb.co/hRpdzdyM/Golden-Bank.png","url":"https://jiligames.com/PlusTrial/45/my-MM"},
    {"title":"Roma X","img":"https://i.ibb.co/XZScHzhY/Roma-X.png","url":"https://jiligames.com/PlusTrial/102/my-MM"},
    {"title":"Wild Ace","img":"https://i.ibb.co/qYWBZNYh/Wild-Ace.png","url":"https://jiligames.com/PlusTrial/181/my-MM"},
    {"title":"SevenSevenSeven","img":"https://i.ibb.co/DfWG52HT/Seven-Seven-Seven.png","url":"https://jiligames.com/PlusTrial/27/my-MM"},
    {"title":"Party Night","img":"https://i.ibb.co/zVhGT8mt/Party-Night.png","url":"https://jiligames.com/PlusTrial/76/my-MM"},
    {"title":"Pharaoh Treasure","img":"https://i.ibb.co/DH2vJ6QS/Pharaoh-Treasure.png","url":"https://jiligames.com/PlusTrial/85/my-MM"},
    {"title":"Crazy Hunter","img":"https://i.ibb.co/bR2wSygx/Crazy-Hunter.png","url":"https://jiligames.com/PlusTrial/92/my-MM"},
    {"title":"Lucky Coming","img":"https://i.ibb.co/Rk7Q2tQQ/Lucky-Coming.png","url":"https://jiligames.com/PlusTrial/91/my-MM"},
    {"title":"Secret Treasure","img":"https://i.ibb.co/QxgrJFM/Secret-Treasure.png","url":"https://jiligames.com/PlusTrial/78/my-MM"},
    {"title":"Book Of Gold","img":"https://i.ibb.co/kV704bp3/Book-Of-Gold.png","url":"https://jiligames.com/PlusTrial/87/my-MM"},
    {"title":"Wild Racer","img":"https://i.ibb.co/dwwtPvjC/Wild-Racer.png","url":"https://jiligames.com/PlusTrial/166/my-MM"},
    {"title":"Medusa","img":"https://i.ibb.co/7JxZjC6D/Medusa.png","url":"https://jiligames.com/PlusTrial/101/my-MM"},
    {"title":"FortunePig","img":"https://i.ibb.co/NdXs6FVC/Fortune-Pig.png","url":"https://jiligames.com/PlusTrial/33/my-MM"},
    {"title":"Fortune Gems 3","img":"https://i.ibb.co/yBWg7FC0/Fortune-Gems-3.png","url":"https://jiligames.com/PlusTrial/300/my-MM","badge":"new"},
    {"title":"Crazy FaFaFa","img":"https://i.ibb.co/6cJHJB88/Crazy-Fa-Fa-Fa.png","url":"https://jiligames.com/PlusTrial/40/my-MM"},
    {"title":"Lucky Ball","img":"https://i.ibb.co/XkpK2954/Lucky-Ball.png","url":"https://jiligames.com/PlusTrial/13/my-MM"},
    {"title":"The Pig House","img":"https://i.ibb.co/nsp9y4HL/The-Pig-House.png","url":"https://jiligames.com/PlusTrial/263/my-MM"},
    {"title":"Dragon Treasure","img":"https://i.ibb.co/tMRcw2n7/Dragon-Treasure.png","url":"https://jiligames.com/PlusTrial/46/my-MM"},
]

# ==================== PG SOFT (20) ====================
PGSOFT_GAMES = [
    {"title":"Mahjong Ways 2","img":"https://i.ibb.co/bMbkhkcn/Mahjong-Ways-2.png","url":"https://api.freedemo.games/launcher/demo/mahjong-ways-2","badge":"hot"},
    {"title":"Lucky Neko","img":"https://i.ibb.co/0kJk2rf/Lucky-Neko.png","url":"https://api.freedemo.games/launcher/demo/lucky-neko"},
    {"title":"Buffalo Win","img":"https://i.ibb.co/p6PwwtwV/Buffalo-Win.png","url":"https://api.freedemo.games/launcher/demo/buffalo-win-infinity-reels"},
    {"title":"Fortune Rabbit","img":"https://i.ibb.co/wNBSV33v/Fortune-Rabbit.png","url":"https://api.freedemo.games/launcher/demo/fortune-rabbit","badge":"hot"},
    {"title":"Chicky Run","img":"https://i.ibb.co/9HRz0mgW/Chicky-Run.png","url":"https://api.freedemo.games/launcher/demo/chicky-run","badge":"new"},
    {"title":"Fortune Dragon","img":"https://i.ibb.co/35vhBnmW/Fortune-Dragon.png","url":"https://api.freedemo.games/launcher/demo/fortune-dragon-pg-soft"},
    {"title":"Fortune Gods","img":"https://i.ibb.co/5XLm1nMj/Fortune-Gods.png","url":"https://api.freedemo.games/launcher/demo/fortune-gods"},
    {"title":"Captains Bounty","img":"https://i.ibb.co/M5xVGC3p/Captains-Bounty.png","url":"https://api.freedemo.games/launcher/demo/captains-bounty"},
    {"title":"Egypt's Book","img":"https://i.ibb.co/JRx9nNyR/Egypt-s-Book-of-Mystery.png","url":"https://api.freedemo.games/launcher/demo/egypts-book-of-mystery"},
    {"title":"Candy Burst","img":"https://i.ibb.co/Q40Gc4S/Candy-Burst.png","url":"https://api.freedemo.games/launcher/demo/candy-burst-pg-soft"},
    {"title":"Queen of Bounty","img":"https://i.ibb.co/MDp5bBsc/Queen-of-Bounty.png","url":"https://api.freedemo.games/launcher/demo/queen-of-bounty"},
    {"title":"Mahjong Ways","img":"https://i.ibb.co/Fb5F27MH/Mahjong-Ways.png","url":"https://api.freedemo.games/launcher/demo/mahjong-ways","badge":"hot"},
    {"title":"Anubis Wrath","img":"https://i.ibb.co/60nVyTLb/Anubis-Wrath.png","url":"https://api.freedemo.games/launcher/demo/anubis-wrath"},
    {"title":"Cai Shen Wins","img":"https://i.ibb.co/M59w9kzf/Cai-Shen-Wins.png","url":"https://m.7ejzzvoy4.com/71/index.html?l=my"},
    {"title":"Hood vs Wolf","img":"https://i.ibb.co/bMbkhkcn/Mahjong-Ways-2.png","url":"https://api.freedemo.games/launcher/demo/hood-vs-wolf"},
    {"title":"Dragon Hatch","img":"https://i.ibb.co/35vhBnmW/Fortune-Dragon.png","url":"https://api.freedemo.games/launcher/demo/dragon-hatch"},
    {"title":"Ways of Qilin","img":"https://i.ibb.co/bMbkhkcn/Mahjong-Ways-2.png","url":"https://api.freedemo.games/launcher/demo/ways-of-qilin"},
    {"title":"Wild Bandito","img":"https://i.ibb.co/MDp5bBsc/Queen-of-Bounty.png","url":"https://api.freedemo.games/launcher/demo/wild-bandito"},
    {"title":"Ganesha Gold","img":"https://i.ibb.co/5XLm1nMj/Fortune-Gods.png","url":"https://api.freedemo.games/launcher/demo/ganesha-gold"},
    {"title":"Tree of Fortune","img":"https://i.ibb.co/MDp5bBsc/Queen-of-Bounty.png","url":"https://api.freedemo.games/launcher/demo/tree-of-fortune"},
]

# ==================== BGAMING (15) ====================
BGAMING_GAMES = [
    {"title":"Savage Buffalo Spirit","img":"https://i.ibb.co/nsjQjfZp/Savage-Buffalo-Spirit.png","url":"https://s3.eu-central-1.amazonaws.com/bg-other-interl/demo-interlayer.html?_target=%2Fplay%2FSavageBuffaloSpirit%2FFUN"},
    {"title":"Gold Of Minos","img":"https://i.ibb.co/fzj5T92q/Gold-Of-Minos.png","url":"https://s3.eu-central-1.amazonaws.com/bg-other-interl/demo-interlayer.html?_target=%2Fplay%2FGoldOfMinos%2FFUN"},
    {"title":"Olympus Trueways","img":"https://i.ibb.co/nqBBw626/Olympus-Trueways.png","url":"https://s3.eu-central-1.amazonaws.com/bg-other-interl/demo-interlayer.html?_target=%2Fplay%2FOlympusTrueways%2FFUN","badge":"hot"},
    {"title":"Lucky Lu","img":"https://i.ibb.co/dsR3Z6Wb/Lucky-Lu.png","url":"https://s3.eu-central-1.amazonaws.com/bg-other-interl/demo-interlayer.html?_target=%2Fplay%2FLuckyLu%2FFUN"},
    {"title":"Wild West Trueways","img":"https://i.ibb.co/9kC6mDm9/Wild-West-Trueways.png","url":"https://s3.eu-central-1.amazonaws.com/bg-other-interl/demo-interlayer.html?_target=%2Fplay%2FWildWestTrueways%2FFUN"},
    {"title":"Fishing Club","img":"https://i.ibb.co/35wSqZ7g/Fishing-Club.png","url":"https://s3.eu-central-1.amazonaws.com/bg-other-interl/demo-interlayer.html?_target=%2Fplay%2FFishingClub%2FFUN"},
    {"title":"Elvis Frog Trueways","img":"https://i.ibb.co/nsjQjfZp/Savage-Buffalo-Spirit.png","url":"https://s3.eu-central-1.amazonaws.com/bg-other-interl/demo-interlayer.html?_target=%2Fplay%2FElvisFrogTrueways%2FFUN"},
    {"title":"Bonanza Billion","img":"https://i.ibb.co/fzj5T92q/Gold-Of-Minos.png","url":"https://s3.eu-central-1.amazonaws.com/bg-other-interl/demo-interlayer.html?_target=%2Fplay%2FBonanzaBillion%2FFUN","badge":"new"},
    {"title":"Book of Cats","img":"https://i.ibb.co/dsR3Z6Wb/Lucky-Lu.png","url":"https://s3.eu-central-1.amazonaws.com/bg-other-interl/demo-interlayer.html?_target=%2Fplay%2FBookOfCats%2FFUN"},
    {"title":"Aztec Magic","img":"https://i.ibb.co/nqBBw626/Olympus-Trueways.png","url":"https://s3.eu-central-1.amazonaws.com/bg-other-interl/demo-interlayer.html?_target=%2Fplay%2FAztecMagic%2FFUN"},
    {"title":"Miss Cherry Fruits","img":"https://i.ibb.co/9kC6mDm9/Wild-West-Trueways.png","url":"https://s3.eu-central-1.amazonaws.com/bg-other-interl/demo-interlayer.html?_target=%2Fplay%2FMissCherryFruits%2FFUN"},
    {"title":"Aloha King Elvis","img":"https://i.ibb.co/35wSqZ7g/Fishing-Club.png","url":"https://s3.eu-central-1.amazonaws.com/bg-other-interl/demo-interlayer.html?_target=%2Fplay%2FAlohaKingElvis%2FFUN"},
    {"title":"Wild Chicago","img":"https://i.ibb.co/nsjQjfZp/Savage-Buffalo-Spirit.png","url":"https://s3.eu-central-1.amazonaws.com/bg-other-interl/demo-interlayer.html?_target=%2Fplay%2FWildChicago%2FFUN"},
    {"title":"Cricket Star","img":"https://i.ibb.co/fzj5T92q/Gold-Of-Minos.png","url":"https://s3.eu-central-1.amazonaws.com/bg-other-interl/demo-interlayer.html?_target=%2Fplay%2FCricketStar%2FFUN"},
    {"title":"Deep Sea","img":"https://i.ibb.co/35wSqZ7g/Fishing-Club.png","url":"https://s3.eu-central-1.amazonaws.com/bg-other-interl/demo-interlayer.html?_target=%2Fplay%2FDeepSea%2FFUN"},
]

# ==================== HABANERO (15) ====================
HABANERO_GAMES = [
    {"title":"Hot Hot Fruit","img":"https://i.ibb.co/q3br7FMz/Sweet-Bonanza.png","url":"https://demo.habanerogames.com/games/hot-hot-fruit/","badge":"hot"},
    {"title":"Fa Cai Shen","img":"https://i.ibb.co/M59w9kzf/Cai-Shen-Wins.png","url":"https://demo.habanerogames.com/games/fa-cai-shen/"},
    {"title":"Hot Hot Summer","img":"https://i.ibb.co/Y7BqkTRC/Money-Coming.png","url":"https://demo.habanerogames.com/games/hot-hot-summer/"},
    {"title":"Koi Gate","img":"https://i.ibb.co/zWwqTByT/Fish-Prawn-Crab.png","url":"https://demo.habanerogames.com/games/koi-gate/","badge":"hot"},
    {"title":"Five Lucky","img":"https://i.ibb.co/n8fn7MJz/Fortune-Gems.png","url":"https://demo.habanerogames.com/games/five-lucky/"},
    {"title":"Lucky Fortunes","img":"https://i.ibb.co/Y7BqkTRC/Money-Coming.png","url":"https://demo.habanerogames.com/games/lucky-fortunes/"},
    {"title":"Dragon Tiger Luck","img":"https://i.ibb.co/tMRcw2n7/Dragon-Treasure.png","url":"https://demo.habanerogames.com/games/dragon-tiger-luck/"},
    {"title":"Rolling Roger","img":"https://i.ibb.co/wZh9w0DZ/Money-Pot.png","url":"https://demo.habanerogames.com/games/rolling-roger/"},
    {"title":"Naughty Nemo","img":"https://i.ibb.co/1f6VxLND/Happy-Fishing.png","url":"https://demo.habanerogames.com/games/naughty-nemo/"},
    {"title":"Mow Money","img":"https://i.ibb.co/Q37L44t6/Coin-Tree.png","url":"https://demo.habanerogames.com/games/mow-money/"},
    {"title":"Panda Panda","img":"https://i.ibb.co/JjHSbJdz/Bao-boon-chin.png","url":"https://demo.habanerogames.com/games/panda-panda/"},
    {"title":"Fruit Punch","img":"https://i.ibb.co/q3br7FMz/Sweet-Bonanza.png","url":"https://demo.habanerogames.com/games/fruit-punch/"},
    {"title":"12 Zodiacs","img":"https://i.ibb.co/tMRcw2n7/Dragon-Treasure.png","url":"https://demo.habanerogames.com/games/12-zodiacs/"},
    {"title":"Indian Cash Catcher","img":"https://i.ibb.co/M59w9kzf/Cai-Shen-Wins.png","url":"https://demo.habanerogames.com/games/indian-cash-catcher/"},
    {"title":"Orient Express","img":"https://i.ibb.co/z383NVV/Gates-of-Hades.png","url":"https://demo.habanerogames.com/games/orient-express/"},
]

# ==================== MASTER DICT ====================
DEFAULT_GAMES = {
    'Pragmatic': PRAGMATIC_GAMES,
    'JILI': JILI_GAMES,
    'PG Soft': PGSOFT_GAMES,
    'BGaming': BGAMING_GAMES,
    'Habanero': HABANERO_GAMES,
}

# Total count
TOTAL_GAMES = sum(len(v) for v in DEFAULT_GAMES.values())